Vagrant.configure(2) do |config|
    config.vm.box = "generic/ubuntu2204"
    #config.vm.box_url = REDACTED

    config.vm.define "mmendiolS" do |control|
        control.vm.hostname = "mmendiolS"
        control.vm.network "private_network", ip: "192.168.56.110"
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "mmendiolS"]
            v.memory = 1024
            v.cpus = 1
        end

        control.vm.provision "shell", path: "./scripts/server.sh"
    end

    config.vm.define "mmendiolSW" do |control|
        control.vm.hostname = "mmendiolSW"
        control.vm.network "private_network", ip: "192.168.56.111"
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "mmendiolSW"]
            v.memory = 1024
            v.cpus = 1
        end

        control.vm.provision "shell", path: "./scripts/worker.sh"
    end
end