Vagrant.configure(2) do |config|
    config.vm.box = "generic/ubuntu2404"
    #config.vm.box_url = REDACTED

    config.vm.define "mmendiolS" do |control|
        control.vm.hostname = "mmendiolS"
        control.vm.network "private_network", ip: "192.168.56.110"
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "mmendiolS"]
            v.memory = 512
            v.cpus = 1
        end

        config.vm.provision :shell, :inline => SHELL
        control.vm.provision "shell", path: REDACTED
    end

    config.vm.define "mmendiolSW" do |control|
        control.vm.hostname = "mmendiolSW"
        control.vm.network "private_network", ip: "192.168.56.111"
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "mmendiolSW"]
            v.memory = 512
            v.cpus = 1
        end

        config.vm.provision "shell", inline: <<-SHELL
        control.vm.provision "shell", path: REDACTED
    end
end